import { useState, useEffect } from "react";
import { Link, useNavigate } from "react-router-dom";
import MarketingNav from "@/components/marketing/MarketingNav";

const HF = "'Bricolage Grotesque', sans-serif";
const BF = "'Inter', sans-serif";
const P = "#4F46E5";
const tint = { indigo: "linear-gradient(135deg, #EEF2FF, #E0E7FF)", mint: "linear-gradient(135deg, #ECFDF5, #D1FAE5)", peach: "linear-gradient(135deg, #FFF7ED, #FED7AA)", pink: "linear-gradient(135deg, #FDF2F8, #FCE7F3)" };

function Sq({ top, left, right, bottom, size = 28, rotate = 12 }: any) { const p: any = {}; if (top != null) p.top = top; if (left != null) p.left = left; if (right != null) p.right = right; if (bottom != null) p.bottom = bottom; return <div style={{ position: "absolute", width: size, height: size, borderRadius: size * 0.25, border: "1.5px dashed rgba(79,70,229,0.1)", transform: `rotate(${rotate}deg)`, pointerEvents: "none", ...p }} />; }
function Dots({ o = 0.2 }: { o?: number }) { return <div style={{ position: "absolute", inset: 0, pointerEvents: "none", opacity: o, backgroundImage: "radial-gradient(circle, rgba(79,70,229,0.1) 1px, transparent 1px)", backgroundSize: "32px 32px" }} />; }
function Pill({ children }: any) { return <span style={{ display: "inline-flex", alignItems: "center", gap: 6, padding: "7px 18px", borderRadius: 99, fontSize: 13, fontWeight: 600, fontFamily: BF, background: "#EEF2FF", color: P, border: "1px solid #C7D2FE" }}>{children}</span>; }
function Btn({ children, v = "p", sz = "m", style: sx, onClick }: any) { const pad: any = { s: "10px 24px", m: "14px 34px", l: "17px 42px" }[sz]; const fs: any = { s: 14, m: 15, l: 16 }[sz]; const vars: any = { p: { background: "linear-gradient(135deg,#4F46E5,#7C3AED)", color: "#fff", border: "none", boxShadow: "0 6px 28px rgba(79,70,229,0.28)" }, o: { background: "#fff", color: "#111827", border: "1.5px solid #E5E7EB", boxShadow: "0 2px 8px rgba(0,0,0,0.04)" } }; return <button onClick={onClick} style={{ display: "inline-flex", alignItems: "center", justifyContent: "center", gap: 8, fontFamily: BF, fontWeight: 600, cursor: "pointer", borderRadius: 99, transition: "all 0.25s", padding: pad, fontSize: fs, ...vars[v], ...sx }}>{children}</button>; }
const ic = { chev: <svg width="10" height="6" viewBox="0 0 10 6" fill="none"><path d="M1 1l4 4 4-4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /></svg> };
function MovingPattern() { return <div style={{ position: "absolute", inset: 0, overflow: "hidden", pointerEvents: "none" }}><div className="orb orb-1" style={{ position: "absolute", width: 600, height: 600, borderRadius: "50%", background: "radial-gradient(circle, rgba(129,140,248,0.4) 0%, rgba(99,102,241,0.12) 40%, transparent 70%)", top: "-15%", left: "-10%", filter: "blur(40px)" }} /><div className="orb orb-2" style={{ position: "absolute", width: 500, height: 500, borderRadius: "50%", background: "radial-gradient(circle, rgba(167,139,250,0.35) 0%, rgba(139,92,246,0.1) 40%, transparent 70%)", top: "15%", right: "-12%", filter: "blur(30px)" }} /><div className="orb orb-3" style={{ position: "absolute", width: 450, height: 450, borderRadius: "50%", background: "radial-gradient(circle, rgba(165,180,252,0.35) 0%, rgba(99,102,241,0.1) 40%, transparent 70%)", bottom: "5%", left: "25%", filter: "blur(35px)" }} /><div className="grid-drift" style={{ position: "absolute", inset: "-50%", width: "200%", height: "200%", opacity: 0.18, backgroundImage: "linear-gradient(rgba(165,180,252,0.3) 1px, transparent 1px), linear-gradient(90deg, rgba(165,180,252,0.3) 1px, transparent 1px)", backgroundSize: "80px 80px" }} /></div>; }

const ANIM_CSS = `
@keyframes gradientShift{0%{background-position:0% 50%}50%{background-position:100% 50%}100%{background-position:0% 50%}}
@keyframes orbFloat1{0%,100%{transform:translate(0,0) scale(1)}25%{transform:translate(60px,40px) scale(1.1)}50%{transform:translate(20px,80px) scale(0.95)}75%{transform:translate(-40px,30px) scale(1.05)}}
@keyframes orbFloat2{0%,100%{transform:translate(0,0) scale(1)}25%{transform:translate(-50px,60px) scale(1.08)}50%{transform:translate(-80px,20px) scale(0.92)}75%{transform:translate(-20px,-40px) scale(1.03)}}
@keyframes orbFloat3{0%,100%{transform:translate(0,0) scale(1)}33%{transform:translate(70px,-30px) scale(1.12)}66%{transform:translate(-30px,-60px) scale(0.9)}}
@keyframes gridDrift{0%{transform:translate(0,0)}100%{transform:translate(60px,60px)}}
@keyframes float{0%,100%{transform:translateY(0)}50%{transform:translateY(-6px)}}
@keyframes colorPulse{0%,100%{box-shadow:0 0 0 0 rgba(255,255,255,0.4)}50%{box-shadow:0 0 0 6px rgba(255,255,255,0)}}
.orb-1{animation:orbFloat1 8s ease-in-out infinite}.orb-2{animation:orbFloat2 10s ease-in-out infinite}.orb-3{animation:orbFloat3 7s ease-in-out infinite}.grid-drift{animation:gridDrift 8s linear infinite}
.hw-card{transition:all 0.3s ease}.hw-card:hover{transform:translateY(-4px);box-shadow:0 16px 40px rgba(0,0,0,0.08)!important}
.hiw-bg{background:linear-gradient(270deg,#E0E7FF,#C7D2FE,#DDD6FE,#C7D2FE,#E0E7FF);background-size:400% 400%;animation:gradientShift 8s ease infinite}
.bento-card{transition:all 0.4s cubic-bezier(0.4,0,0.2,1)}.bento-card:hover{transform:translateY(-8px);box-shadow:0 24px 56px rgba(79,70,229,0.12)!important;border-color:#C7D2FE!important}
.color-dot{cursor:pointer;transition:all 0.25s ease;border:3px solid transparent}.color-dot:hover{transform:scale(1.15)}.color-dot.active{border-color:#fff;box-shadow:0 0 0 2px rgba(79,70,229,0.6);animation:colorPulse 2s ease infinite}
@keyframes testimonialSlide{0%{transform:translateX(0)}33.33%{transform:translateX(0)}38.33%{transform:translateX(-33.33%)}66.66%{transform:translateX(-33.33%)}71.66%{transform:translateX(-66.66%)}100%{transform:translateX(-66.66%)}}.testi-track{animation:testimonialSlide 9s ease-in-out infinite}
`;

const STORE_THEMES = [
  { name: "DTF Prints", color: "#4F46E5", bg: "#EEF2FF", slug: "dtf-prints", products: ["Standard DTF", "Premium DTF", "Glow in Dark"] },
  { name: "Elite DTF", color: "#059669", bg: "#ECFDF5", slug: "elite-dtf", products: ["Economy Pack", "Pro Transfer", "Metallic Finish"] },
  { name: "Print Lab", color: "#E11D48", bg: "#FFF1F2", slug: "print-lab", products: ["Matte DTF", "Glossy DTF", "Neon Transfer"] },
  { name: "Ink Masters", color: "#D97706", bg: "#FFFBEB", slug: "ink-masters", products: ["Basic Sheet", "Bulk Bundle", "Custom Size"] },
  { name: "DTF Pro", color: "#0891B2", bg: "#ECFEFF", slug: "dtf-pro", products: ["Single Print", "Gang Sheet", "Rush Order"] },
];

function HeroShot({ themeIdx }: { themeIdx: number }) {
  const t = STORE_THEMES[themeIdx];
  return (
    <div style={{ borderRadius: 16, overflow: "hidden", background: "#fff", border: "1px solid rgba(79,70,229,0.08)", boxShadow: "0 50px 120px rgba(79,70,229,0.12)" }}>
      <div style={{ display: "flex", alignItems: "center", padding: "10px 16px", background: "#FAFBFD", borderBottom: "1px solid #EEF0F4" }}>
        <div style={{ display: "flex", gap: 6, marginRight: 16 }}>{["#FF5F57", "#FFBD2E", "#28C840"].map((c, i) => <div key={i} style={{ width: 11, height: 11, borderRadius: "50%", background: c }} />)}</div>
        <div style={{ flex: 1, height: 28, background: "#F3F4F6", borderRadius: 8, display: "flex", alignItems: "center", justifyContent: "center" }}><svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="#9CA3AF" strokeWidth="2" style={{ marginRight: 6 }}><rect x="3" y="11" width="18" height="11" rx="2" /><path d="M7 11V7a5 5 0 0110 0v4" /></svg><span style={{ fontSize: 12, color: "#9CA3AF", fontWeight: 500, fontFamily: BF, transition: "all 0.4s" }}>{t.slug}.dtflayout.com</span></div>
      </div>
      <div style={{ background: t.color, padding: "10px 20px", display: "flex", alignItems: "center", justifyContent: "space-between", transition: "background 0.4s" }}><div style={{ display: "flex", alignItems: "center", gap: 8 }}><div style={{ width: 26, height: 26, borderRadius: 7, background: "rgba(255,255,255,0.2)", display: "flex", alignItems: "center", justifyContent: "center" }}><svg width="12" height="12" viewBox="0 0 24 24" fill="#fff"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z" /></svg></div><span style={{ fontSize: 14, fontWeight: 700, color: "#fff", fontFamily: HF, transition: "all 0.4s" }}>{t.name}</span></div><div style={{ display: "flex", gap: 16 }}>{["Products", "About", "Contact"].map((l, i) => <span key={i} style={{ fontSize: 11, color: "rgba(255,255,255,0.75)", fontWeight: 500 }}>{l}</span>)}</div></div>
      <div style={{ background: `linear-gradient(135deg, ${t.color}22, ${t.color}44)`, padding: "24px 24px 20px", textAlign: "center", transition: "background 0.4s" }}><div style={{ fontSize: 20, fontWeight: 800, color: "#111827", fontFamily: HF, marginBottom: 4 }}>Welcome to {t.name}</div><div style={{ fontSize: 11, color: "#6B7280", marginBottom: 12 }}>Premium DTF transfers with fast turnaround. Upload your designs, we handle the rest.</div><div style={{ display: "inline-flex", padding: "6px 18px", borderRadius: 8, background: t.color, fontSize: 11, fontWeight: 600, color: "#fff", transition: "background 0.4s" }}>Browse Products</div></div>
      <div style={{ padding: "14px 16px 16px", background: "#FAFBFD" }}><div style={{ fontSize: 13, fontWeight: 700, color: "#111827", fontFamily: HF, marginBottom: 10 }}>Our Products</div><div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 8 }}>{t.products.map((p, i) => (<div key={i} style={{ background: "#fff", borderRadius: 10, border: "1px solid #E5E7EB", overflow: "hidden" }}><div style={{ height: 48, background: `linear-gradient(135deg, ${t.color}18, ${t.color}35)`, display: "flex", alignItems: "center", justifyContent: "center", transition: "background 0.4s" }}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke={t.color} strokeWidth="1.5" style={{ transition: "stroke 0.4s" }}><rect x="3" y="3" width="18" height="18" rx="2" /><circle cx="8.5" cy="8.5" r="1.5" /><polyline points="21 15 16 10 5 21" /></svg></div><div style={{ padding: "8px 10px" }}><div style={{ fontSize: 10, fontWeight: 700, color: "#111827" }}>{p}</div><div style={{ fontSize: 8, color: "#9CA3AF", marginTop: 2 }}>From $0.03/sq.in</div><div style={{ marginTop: 6, padding: "4px 0", borderRadius: 5, background: t.color, fontSize: 8, fontWeight: 600, color: "#fff", textAlign: "center", transition: "background 0.4s" }}>Create Sheet</div></div></div>))}</div></div>
    </div>
  );
}

export default function QuickStore() {
  const navigate = useNavigate();

  const [isMobile, setIsMobile] = useState(typeof window !== "undefined" ? window.innerWidth < 768 : false);
  useEffect(() => { const h = () => setIsMobile(window.innerWidth < 768); window.addEventListener("resize", h); return () => window.removeEventListener("resize", h); }, []);

  const [themeIdx, setThemeIdx] = useState(0);
  const [autoCycle, setAutoCycle] = useState(true);
  useEffect(() => { const l1 = document.createElement("link"); l1.href = "https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:wght@400;600;700;800&family=Inter:wght@400;500;600;700&display=swap"; l1.rel = "stylesheet"; document.head.appendChild(l1); return () => { document.head.removeChild(l1); }; }, []);
  useEffect(() => { if (!autoCycle) return; const t = setInterval(() => { setThemeIdx(p => (p + 1) % STORE_THEMES.length); }, 2500); return () => clearInterval(t); }, [autoCycle]);
  const pickTheme = (i: number) => { setAutoCycle(false); setThemeIdx(i); };
  const st = STORE_THEMES[themeIdx];

  return (
    <div style={{ fontFamily: BF, color: "#111827", overflowX: "hidden" }}>
      <style>{ANIM_CSS}</style>

      {/* NAV */}
      <MarketingNav />

      {/* HERO */}
      <section style={{ position: "relative", overflow: "hidden", background: "linear-gradient(180deg, #0A0820 0%, #0F0D2E 12%, #1E1B4B 24%, #312E81 36%, #4F46E5 48%, #6366F1 55%, #818CF8 62%, #A5B4FC 68%, #C7D2FE 74%, #E0E7FF 80%, #EEF2FF 86%, #F5F5F7 92%, #FAFAFB 100%)", padding: isMobile ? "0 16px 0" : "0 40px 0" }}><Dots o={0.04} /><MovingPattern /><div style={{ padding: isMobile ? "100px 0 0" : "140px 0 0" }}><Sq top={20} right={140} size={32} rotate={18} /><Sq top={100} right={80} size={22} rotate={-12} /><Sq top={30} left={100} size={28} rotate={22} /><div style={{ position: "relative", zIndex: 2, maxWidth: 720, margin: "0 auto", textAlign: "center" }}><Pill><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke={P} strokeWidth="2" style={{ marginRight: 2 }}><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" /><polyline points="9 22 9 12 15 12 15 22" /></svg> Quick Store</Pill><h1 style={{ fontFamily: HF, fontSize: isMobile ? 56 : 60, fontWeight: 800, color: "#fff", lineHeight: 1.08, letterSpacing: "-0.03em", margin: "28px 0 20px" }}>No Website? No Problem.<br />We'll Build You One.</h1><p style={{ fontSize: 17, color: "rgba(255,255,255,0.75)", lineHeight: 1.7, maxWidth: 560, margin: "0 auto 36px" }}>Get a complete, professional website for your DTF printing business — free to set up. Your customers browse products, create gang sheets, and place orders — all at your own URL.</p><div style={{ display: "flex", justifyContent: "center", gap: 14 }}><Btn sz="l" onClick={() => navigate("/signup")} style={{ background: "#fff", color: P, boxShadow: "0 6px 28px rgba(0,0,0,0.15)" }}>Launch Your Store Free →</Btn><Btn v="o" sz="l" style={{ background: "transparent", color: "#fff", borderColor: "rgba(255,255,255,0.3)", boxShadow: "none" }} onClick={() => navigate("/pricing")}>View Pricing →</Btn></div></div><div style={{ position: "relative", zIndex: 2, maxWidth: 780, margin: "72px auto 0" }}><HeroShot themeIdx={themeIdx} /><div style={{ display: "flex", justifyContent: "center", gap: 12, marginTop: 20, marginBottom: 8 }}><span style={{ fontSize: 12, color: "#9CA3AF", fontWeight: 500, alignSelf: "center" }}>Try a store theme:</span>{STORE_THEMES.map((c, i) => <div key={i} className={`color-dot ${themeIdx === i ? "active" : ""}`} onClick={() => pickTheme(i)} style={{ width: 28, height: 28, borderRadius: "50%", background: c.color }} title={c.name}></div>)}</div></div><div style={{ height: 120, background: "linear-gradient(180deg, transparent, #FAFAFB)" }} /></div></section>

      {/* HOW IT WORKS — 3 Detailed Alternating Steps */}
      <section style={{ padding: isMobile ? "60px 16px" : "120px 40px", position: "relative" }}><Dots o={0.08} /><Sq top={80} right={120} size={32} rotate={18} /><Sq bottom={90} left={100} size={24} rotate={-15} /><div style={{ maxWidth: 1060, margin: "0 auto", position: "relative", zIndex: 1 }}><div style={{ textAlign: "center", marginBottom: 64 }}><Pill>Quick Setup</Pill><h2 style={{ fontFamily: HF, fontSize: isMobile ? 26 : 44, fontWeight: 800, color: "#111827", lineHeight: 1.1, letterSpacing: "-0.03em", margin: "20px 0 12px" }}>Live in 3 Simple Steps</h2><p style={{ fontSize: 16, color: "#6B7280", lineHeight: 1.7, maxWidth: 520, margin: "0 auto" }}>No coding. No hosting. No domain purchase. Just set up and share.</p></div>
        {/* Step 1 — Store Setup */}
        <div style={{ display: "grid", gridTemplateColumns: isMobile ? "1fr" : "1fr 1.2fr", gap: 32, marginBottom: 72, alignItems: "center" }}>
          <div><div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 20 }}><div style={{ width: 44, height: 44, borderRadius: 12, background: "linear-gradient(135deg,#4F46E5,#7C3AED)", display: "flex", alignItems: "center", justifyContent: "center", color: "#fff", fontSize: 18, fontWeight: 800, fontFamily: HF }}>1</div><h3 style={{ fontFamily: HF, fontSize: 28, fontWeight: 800, color: "#111827", margin: 0 }}>Set Up Your Store</h3></div><p style={{ fontSize: 15, color: "#6B7280", lineHeight: 1.7, margin: "0 0 20px" }}>Pick a store name, upload your logo, choose from 10+ font pairings, and set your brand colors. Your website goes live instantly at your-store.dtflayout.com — no domain purchase needed.</p><div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>{["Store Name & URL", "Logo Upload", "10+ Font Pairings", "Brand Colors", "Business Hours", "Contact Info"].map((t, i) => <span key={i} style={{ padding: "6px 14px", borderRadius: 99, fontSize: 12, fontWeight: 600, background: "#EEF2FF", color: P, border: "1px solid #C7D2FE" }}>{t}</span>)}</div></div>
          <div className="bento-card" style={{ background: "#fff", borderRadius: 20, border: "1px solid #E5E7EB", boxShadow: "0 2px 8px rgba(0,0,0,0.02)", overflow: "hidden" }}><div style={{ padding: 20 }}><div style={{ background: tint.indigo, borderRadius: 14, padding: 20 }}>
            <div style={{ fontSize: 11, fontWeight: 700, color: "#111827", marginBottom: 14, fontFamily: HF }}>Store Setup</div>
            {[{ l: "Store Name", v: "DTF Prints" }, { l: "Tagline", v: "Quality DTF Printing" }].map((f, i) => <div key={i} style={{ marginBottom: 10 }}><div style={{ fontSize: 8, color: "#9CA3AF", fontWeight: 600, marginBottom: 3, textTransform: "uppercase" }}>{f.l}</div><div style={{ background: "#fff", borderRadius: 8, padding: "8px 12px", border: "1px solid rgba(0,0,0,0.06)", fontSize: 12, fontWeight: 500, color: "#111827" }}>{f.v}</div></div>)}
            <div style={{ background: "rgba(79,70,229,0.06)", borderRadius: 10, padding: "10px 14px", border: "1px solid rgba(79,70,229,0.12)", marginBottom: 14 }}><div style={{ fontSize: 8, color: "#9CA3AF", fontWeight: 600, marginBottom: 3 }}>YOUR STORE URL</div><div style={{ display: "flex", alignItems: "center", gap: 6 }}><span style={{ fontSize: 11, color: P, fontFamily: "monospace", fontWeight: 600 }}>dtf-prints.dtflayout.com</span><svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="#16A34A" strokeWidth="2.5"><path d="M5 13l4 4L19 7" /></svg></div></div>
            <div style={{ display: "grid", gridTemplateColumns: "48px 1fr", gap: 10, alignItems: "center", marginBottom: 14 }}><div style={{ width: 48, height: 48, borderRadius: 10, border: "2px dashed #C7D2FE", display: "flex", alignItems: "center", justifyContent: "center", background: "#fff" }}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#A5B4FC" strokeWidth="2"><rect x="3" y="3" width="18" height="18" rx="2" /><circle cx="8.5" cy="8.5" r="1.5" /><polyline points="21 15 16 10 5 21" /></svg></div><div><div style={{ fontSize: 8, color: "#9CA3AF", fontWeight: 600, textTransform: "uppercase" }}>Store Logo</div><div style={{ fontSize: 11, color: P, fontWeight: 600 }}>Upload your logo</div></div></div>
            <div style={{ fontSize: 8, color: "#9CA3AF", fontWeight: 600, marginBottom: 6, textTransform: "uppercase" }}>Font Style</div>
            <div style={{ display: "grid", gridTemplateColumns: isMobile ? "1fr" : "1fr 1fr 1fr", gap: 6, marginBottom: 14 }}>{[{ l: "Modern", f: "Inter", sel: true }, { l: "Classic", f: "Playfair", sel: false }, { l: "Bold", f: "Poppins", sel: false }].map((f, i) => <div key={i} style={{ background: f.sel ? "rgba(79,70,229,0.08)" : "#fff", borderRadius: 8, padding: "8px 10px", border: `1px solid ${f.sel ? "rgba(79,70,229,0.25)" : "rgba(0,0,0,0.04)"}`, textAlign: "center", position: "relative" }}>{f.sel && <div style={{ position: "absolute", top: 4, right: 4, width: 14, height: 14, borderRadius: "50%", background: P, display: "flex", alignItems: "center", justifyContent: "center" }}><svg width="8" height="8" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="3"><path d="M5 13l4 4L19 7" /></svg></div>}<div style={{ fontSize: 11, fontWeight: 700, color: "#111827" }}>{f.l}</div><div style={{ fontSize: 8, color: "#9CA3AF" }}>{f.f}</div></div>)}</div>
            <div style={{ fontSize: 8, color: "#9CA3AF", fontWeight: 600, marginBottom: 6, textTransform: "uppercase" }}>Brand Colors</div>
            <div style={{ display: "flex", gap: 8 }}>{[{ l: "Primary", c: "#4F46E5" }, { l: "Secondary", c: "#3B82F6" }, { l: "Background", c: "#FFFFFF" }, { l: "Text", c: "#1F2937" }].map((c, i) => <div key={i} style={{ textAlign: "center" }}><div style={{ width: 32, height: 32, borderRadius: 8, background: c.c, border: "1px solid rgba(0,0,0,0.08)", marginBottom: 2 }} /><div style={{ fontSize: 7, color: "#6B7280" }}>{c.l}</div></div>)}</div>
          </div></div></div>
        </div>
        {/* Step 2 — Products & Pricing */}
        <div style={{ display: "grid", gridTemplateColumns: isMobile ? "1fr" : "1.2fr 1fr", gap: 32, marginBottom: 72, alignItems: "center" }}>
          <div className="bento-card" style={{ background: "#fff", borderRadius: 20, border: "1px solid #E5E7EB", boxShadow: "0 2px 8px rgba(0,0,0,0.02)", overflow: "hidden" }}><div style={{ padding: 20 }}><div style={{ background: tint.mint, borderRadius: 14, padding: 20 }}>
            <div style={{ fontSize: 11, fontWeight: 700, color: "#111827", marginBottom: 14, fontFamily: HF }}>Product Setup — DTF Gang Sheet Builder</div>
            <div style={{ fontSize: 8, color: "#9CA3AF", fontWeight: 600, marginBottom: 6, textTransform: "uppercase" }}>Pricing Basis</div>
            <div style={{ display: "flex", gap: 6, marginBottom: 14 }}>{["Per inch (length)", "Per sq.inch (area)"].map((l, i) => <span key={i} style={{ flex: 1, padding: "8px 0", borderRadius: 8, fontSize: 10, fontWeight: 600, background: i === 1 ? P : "#fff", color: i === 1 ? "#fff" : "#6B7280", textAlign: "center", border: i === 0 ? "1px solid #E5E7EB" : "none" }}>{l}</span>)}</div>
            <div style={{ fontSize: 8, color: "#9CA3AF", fontWeight: 600, marginBottom: 6, textTransform: "uppercase" }}>Pricing Type</div>
            <div style={{ display: "flex", gap: 6, marginBottom: 14 }}>{["Flat Rate", "Tiered (Bulk Discounts)"].map((l, i) => <span key={i} style={{ flex: 1, padding: "8px 0", borderRadius: 8, fontSize: 10, fontWeight: 600, background: i === 1 ? P : "#fff", color: i === 1 ? "#fff" : "#6B7280", textAlign: "center", border: i === 0 ? "1px solid #E5E7EB" : "none" }}>{l}</span>)}</div>
            <div style={{ background: "#fff", borderRadius: 10, overflow: "hidden", border: "1px solid rgba(0,0,0,0.06)", marginBottom: 12 }}><div style={{ display: "grid", gridTemplateColumns: isMobile ? "1fr" : "1fr 1fr 1fr", padding: "6px 12px", background: "#F9FAFB", borderBottom: "1px solid #E5E7EB" }}>{["Range", "Rate", "Type"].map((h, i) => <span key={i} style={{ fontSize: 8, fontWeight: 700, color: "#6B7280", textTransform: "uppercase" }}>{h}</span>)}</div>{[{ r: "0 – 100 sq.in", p: "$0.05", t: "Base" }, { r: "101 – 300 sq.in", p: "$0.04", t: "Bulk" }, { r: "301+ sq.in", p: "$0.03", t: "Volume" }].map((row, i) => <div key={i} style={{ display: "grid", gridTemplateColumns: isMobile ? "1fr" : "1fr 1fr 1fr", padding: "8px 12px", borderBottom: i < 2 ? "1px solid #F3F4F6" : "none" }}><span style={{ fontSize: 10, fontWeight: 600, color: "#111827" }}>{row.r}</span><span style={{ fontSize: 10, fontWeight: 700, color: "#059669" }}>{row.p}</span><span style={{ fontSize: 9, color: "#9CA3AF" }}>{row.t}</span></div>)}</div>
            <div style={{ display: "flex", gap: 8 }}><div style={{ flex: 1 }}><div style={{ fontSize: 8, color: "#9CA3AF", fontWeight: 600, marginBottom: 3, textTransform: "uppercase" }}>Currency</div><div style={{ background: "#fff", borderRadius: 8, padding: "7px 10px", border: "1px solid rgba(0,0,0,0.06)", fontSize: 11, fontWeight: 500, color: "#111827", display: "flex", justifyContent: "space-between" }}>$ – USD {ic.chev}</div></div><div style={{ flex: 1 }}><div style={{ fontSize: 8, color: "#9CA3AF", fontWeight: 600, marginBottom: 3, textTransform: "uppercase" }}>Unit</div><div style={{ background: "#fff", borderRadius: 8, padding: "7px 10px", border: "1px solid rgba(0,0,0,0.06)", fontSize: 11, fontWeight: 500, color: "#111827", display: "flex", justifyContent: "space-between" }}>inches {ic.chev}</div></div></div>
          </div></div></div>
          <div><div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 20 }}><div style={{ width: 44, height: 44, borderRadius: 12, background: "linear-gradient(135deg,#4F46E5,#7C3AED)", display: "flex", alignItems: "center", justifyContent: "center", color: "#fff", fontSize: 18, fontWeight: 800, fontFamily: HF }}>2</div><h3 style={{ fontFamily: HF, fontSize: 28, fontWeight: 800, color: "#111827", margin: 0 }}>Add Products & Pricing</h3></div><p style={{ fontSize: 15, color: "#6B7280", lineHeight: 1.7, margin: "0 0 20px" }}>Create multiple products — Standard DTF, Premium, Glow in Dark — each with its own pricing, images, description, and dedicated builder page. Set pricing your way: flat rate or tiered bulk discounts, charged per-length or per-area.</p><div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>{["Flat or Tiered", "Per-Length / Area", "7 Currencies", "4 Units", "Product Images", "Delivery Timeline"].map((t, i) => <span key={i} style={{ padding: "6px 14px", borderRadius: 99, fontSize: 12, fontWeight: 600, background: "#ECFDF5", color: "#059669", border: "1px solid #A7F3D0" }}>{t}</span>)}</div></div>
        </div>
        {/* Step 3 — Publish & Sell */}
        <div style={{ display: "grid", gridTemplateColumns: isMobile ? "1fr" : "1fr 1.2fr", gap: 32, alignItems: "center" }}>
          <div><div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 20 }}><div style={{ width: 44, height: 44, borderRadius: 12, background: "linear-gradient(135deg,#4F46E5,#7C3AED)", display: "flex", alignItems: "center", justifyContent: "center", color: "#fff", fontSize: 18, fontWeight: 800, fontFamily: HF }}>3</div><h3 style={{ fontFamily: HF, fontSize: 28, fontWeight: 800, color: "#111827", margin: 0 }}>Publish & Start Selling</h3></div><p style={{ fontSize: 15, color: "#6B7280", lineHeight: 1.7, margin: "0 0 20px" }}>Flip the publish toggle and your store is live. Share the link on WhatsApp, social media, your business card — anywhere. Customers browse products, build gang sheets, and submit orders. You track everything from your analytics dashboard.</p><div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>{["One-Click Publish", "Shareable URL", "Conversion Funnel", "Traffic Stats", "No Auth Required"].map((t, i) => <span key={i} style={{ padding: "6px 14px", borderRadius: 99, fontSize: 12, fontWeight: 600, background: "#FFF7ED", color: "#D97706", border: "1px solid #FDE68A" }}>{t}</span>)}</div></div>
          <div className="bento-card" style={{ background: "#fff", borderRadius: 20, border: "1px solid #E5E7EB", boxShadow: "0 2px 8px rgba(0,0,0,0.02)", overflow: "hidden" }}><div style={{ padding: 20 }}><div style={{ background: tint.peach, borderRadius: 14, padding: 20 }}>
            <div style={{ fontSize: 11, fontWeight: 700, color: "#111827", marginBottom: 14, fontFamily: HF }}>Settings & Analytics</div>
            <div style={{ background: "#fff", borderRadius: 10, padding: 12, marginBottom: 12, border: "1px solid rgba(0,0,0,0.04)" }}><div style={{ fontSize: 8, color: "#9CA3AF", fontWeight: 600, marginBottom: 4 }}>STORE URL</div><div style={{ display: "flex", alignItems: "center", gap: 6, background: "#F9FAFB", borderRadius: 6, padding: "6px 10px", border: "1px solid #E5E7EB" }}><span style={{ fontSize: 11, color: P, fontFamily: "monospace", flex: 1 }}>https://dtf-prints.dtflayout.com</span><div style={{ padding: "3px 10px", borderRadius: 5, background: P, fontSize: 8, fontWeight: 700, color: "#fff" }}>Copy</div><div style={{ padding: "3px 10px", borderRadius: 5, background: "#F3F4F6", fontSize: 8, fontWeight: 600, color: "#374151", border: "1px solid #E5E7EB" }}>Open</div></div></div>
            <div style={{ background: "#fff", borderRadius: 10, padding: 12, marginBottom: 12, border: "1px solid rgba(0,0,0,0.04)", display: "flex", alignItems: "center", justifyContent: "space-between" }}><div><div style={{ fontSize: 11, fontWeight: 700, color: "#111827", display: "flex", alignItems: "center", gap: 6 }}><div style={{ width: 8, height: 8, borderRadius: "50%", background: "#16A34A" }} />Store is Live</div><div style={{ fontSize: 8, color: "#9CA3AF" }}>Customers can access your store</div></div><div style={{ width: 36, height: 20, borderRadius: 10, background: P, position: "relative" }}><div style={{ position: "absolute", top: 2, right: 2, width: 16, height: 16, borderRadius: "50%", background: "#fff", boxShadow: "0 1px 3px rgba(0,0,0,0.15)" }} /></div></div>
            <div style={{ fontSize: 8, color: "#9CA3AF", fontWeight: 600, marginBottom: 8, textTransform: "uppercase" }}>Conversion Funnel</div>
            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", background: "#fff", borderRadius: 10, padding: "10px 8px", border: "1px solid rgba(0,0,0,0.04)" }}>{[{ n: "268", l: "Page Views", c: P }, { n: "57", l: "Product Views", c: "#7C3AED" }, { n: "24", l: "Builder Opens", c: "#A855F7" }, { n: "12", l: "Orders", c: "#16A34A" }].map((s, i) => <div key={i} style={{ display: "flex", alignItems: "center" }}><div style={{ textAlign: "center", minWidth: 52 }}><div style={{ fontSize: 16, fontWeight: 800, fontFamily: HF, color: s.c }}>{s.n}</div><div style={{ fontSize: 7, color: "#9CA3AF", marginTop: 1 }}>{s.l}</div></div>{i < 3 && <svg width="14" height="10" viewBox="0 0 14 10" fill="none" style={{ margin: "0 2px", marginBottom: 10 }}><path d="M1 5h10M9 2l3 3-3 3" stroke="#D1D5DB" strokeWidth="1.5" strokeLinecap="round" /></svg>}</div>)}</div>
          </div></div></div>
        </div>
      </div></section>

      {/* YOUR WEBSITE — Rich visual mockup cards */}
      <section style={{ padding: isMobile ? "60px 16px" : "120px 40px", background: "#FAFAFB", position: "relative" }}><Dots o={0.06} /><div style={{ maxWidth: 1060, margin: "0 auto", position: "relative", zIndex: 1 }}><div style={{ textAlign: "center", marginBottom: 64 }}><Pill>Your Website</Pill><h2 style={{ fontFamily: HF, fontSize: isMobile ? 26 : 44, fontWeight: 800, color: "#111827", lineHeight: 1.1, letterSpacing: "-0.03em", margin: "20px 0 12px" }}>Your Website, Ready in Under 30 Minutes</h2><p style={{ fontSize: 16, color: "#6B7280", lineHeight: 1.7, maxWidth: 560, margin: "0 auto" }}>Your customers get a professional website with hero section, product catalog, testimonials, FAQ, contact info, and an embedded gang sheet builder.</p></div>
        <div style={{ display: "grid", gridTemplateColumns: isMobile ? "1fr" : "1fr 1fr", gap: 20 }}>
          {/* Hero Section card */}
          <div className="bento-card" style={{ background: "#fff", borderRadius: 24, border: "1px solid #E5E7EB", overflow: "hidden", boxShadow: "0 2px 8px rgba(0,0,0,0.02)" }}><div style={{ padding: 20 }}><div style={{ background: tint.indigo, borderRadius: 16, padding: 16, overflow: "hidden" }}><div style={{ borderRadius: 10, overflow: "hidden", border: "1px solid rgba(0,0,0,0.06)", marginBottom: 10 }}><div style={{ background: `linear-gradient(135deg, #1E1B4B, ${P})`, padding: "16px 14px", textAlign: "center" }}><div style={{ fontSize: 12, fontWeight: 700, color: "#fff", fontFamily: HF }}>Welcome to DTF Prints</div><div style={{ fontSize: 8, color: "rgba(255,255,255,0.7)", margin: "3px 0 8px" }}>Premium DTF transfers with fast turnaround</div><div style={{ display: "inline-flex", padding: "4px 14px", borderRadius: 6, background: "#fff", fontSize: 8, fontWeight: 600, color: P }}>View Products</div></div></div><div style={{ fontSize: 8, color: "#6B7280", fontWeight: 600, marginBottom: 6 }}>5 HERO STYLES</div><div style={{ display: "flex", gap: 4 }}>{[{ l: "Full Bleed", bg: `linear-gradient(135deg,#1E1B4B,${P})`, sel: true }, { l: "Split", bg: "linear-gradient(90deg,#F3F4F6 50%,#F59E0B 50%)", sel: false }, { l: "Minimal", bg: "#F9FAFB", sel: false }, { l: "Cinematic", bg: "linear-gradient(135deg,#92400E,#F59E0B)", sel: false }, { l: "Card", bg: "linear-gradient(135deg,#059669,#34D399)", sel: false }].map((s, i) => <div key={i} style={{ flex: 1, textAlign: "center" }}><div style={{ height: 24, borderRadius: 4, background: s.bg, border: s.sel ? `2px solid ${P}` : "1px solid #E5E7EB", marginBottom: 2 }} /><div style={{ fontSize: 6, color: s.sel ? P : "#9CA3AF", fontWeight: 600 }}>{s.l}</div></div>)}</div></div></div><div style={{ padding: "0 28px 28px" }}><h3 style={{ fontFamily: HF, fontSize: 20, fontWeight: 700, margin: "0 0 8px", color: "#111827" }}>Hero Section & Branding</h3><p style={{ fontSize: 14, color: "#6B7280", lineHeight: 1.65, margin: 0 }}>Full-width hero with 5 styles, gradient/solid/image backgrounds, custom headline, subtitle, CTA button, and text alignment options.</p></div></div>
          {/* Product Catalog card */}
          <div className="bento-card" style={{ background: "#fff", borderRadius: 24, border: "1px solid #E5E7EB", overflow: "hidden", boxShadow: "0 2px 8px rgba(0,0,0,0.02)" }}><div style={{ padding: 20 }}><div style={{ background: tint.mint, borderRadius: 16, padding: 16 }}><div style={{ fontSize: 8, color: "#6B7280", fontWeight: 600, marginBottom: 8 }}>PRODUCT CATALOG</div><div style={{ display: "grid", gridTemplateColumns: isMobile ? "1fr" : "repeat(3,1fr)", gap: 6 }}>{[{ n: "Standard DTF", p: "$0.03/sq.in", c: "#059669" }, { n: "Premium DTF", p: "$0.05/sq.in", c: "#7C3AED" }, { n: "Glow in Dark", p: "$0.08/sq.in", c: "#D97706" }].map((prod, i) => <div key={i} style={{ background: "#fff", borderRadius: 8, border: "1px solid rgba(0,0,0,0.06)", overflow: "hidden" }}><div style={{ height: 36, background: `linear-gradient(135deg, ${prod.c}18, ${prod.c}35)`, display: "flex", alignItems: "center", justifyContent: "center" }}><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke={prod.c} strokeWidth="1.5"><rect x="3" y="3" width="18" height="18" rx="2" /><circle cx="8.5" cy="8.5" r="1.5" /><polyline points="21 15 16 10 5 21" /></svg></div><div style={{ padding: "6px 8px" }}><div style={{ fontSize: 9, fontWeight: 700, color: "#111827" }}>{prod.n}</div><div style={{ fontSize: 7, color: "#9CA3AF", marginTop: 1 }}>{prod.p}</div><div style={{ marginTop: 4, padding: "3px 0", borderRadius: 4, background: prod.c, fontSize: 7, fontWeight: 600, color: "#fff", textAlign: "center" }}>Create Sheet</div></div></div>)}</div><div style={{ display: "flex", gap: 4, marginTop: 8 }}>{["Per-Length", "Per-Area", "Flat", "Tiered"].map((t, i) => <span key={i} style={{ padding: "2px 8px", borderRadius: 99, fontSize: 7, fontWeight: 600, background: "#fff", color: "#059669", border: "1px solid #A7F3D0" }}>{t}</span>)}</div></div></div><div style={{ padding: "0 28px 28px" }}><h3 style={{ fontFamily: HF, fontSize: 20, fontWeight: 700, margin: "0 0 8px", color: "#111827" }}>Product Catalog</h3><p style={{ fontSize: 14, color: "#6B7280", lineHeight: 1.65, margin: 0 }}>Multiple products per store, each with its own pricing, images, description, delivery timeline, and dedicated builder page.</p></div></div>
          {/* Testimonials card — sliding carousel */}
          <div className="bento-card" style={{ background: "#fff", borderRadius: 24, border: "1px solid #E5E7EB", overflow: "hidden", boxShadow: "0 2px 8px rgba(0,0,0,0.02)" }}><div style={{ padding: 20 }}><div style={{ background: tint.peach, borderRadius: 16, padding: 16, overflow: "hidden" }}><div style={{ fontSize: 8, color: "#6B7280", fontWeight: 600, marginBottom: 8 }}>CUSTOMER REVIEWS</div><div style={{ overflow: "hidden", borderRadius: 10 }}><div className="testi-track" style={{ display: "flex", width: "300%" }}>{[{ n: "Alex Rivera", loc: "Texas, USA", q: "Gang sheets perfectly arranged with zero wasted space. Will order again!", av: "#E74C3C" }, { n: "Sarah Mitchell", loc: "London, UK", q: "Color vibrancy is amazing, transfers adhered perfectly to fabric.", av: "#3498DB" }, { n: "James Chen", loc: "Toronto, CA", q: "The online builder is so easy. Customer support is super responsive!", av: "#2ECC71" }].map((rev, i) => <div key={i} style={{ width: "33.33%", padding: "0 4px", boxSizing: "border-box" as const, flexShrink: 0 }}><div style={{ background: "#fff", borderRadius: 10, padding: "12px 14px", border: "1px solid rgba(0,0,0,0.06)", height: "100%" }}><div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 8 }}><div style={{ width: 28, height: 28, borderRadius: "50%", background: `linear-gradient(135deg, ${rev.av}, ${rev.av}88)`, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}><span style={{ fontSize: 11, fontWeight: 700, color: "#fff" }}>{rev.n[0]}</span></div><div><div style={{ fontSize: 10, fontWeight: 700, color: "#111827" }}>{rev.n}</div><div style={{ fontSize: 7, color: "#9CA3AF" }}>{rev.loc}</div></div></div><div style={{ display: "flex", gap: 1, marginBottom: 6 }}>{[0,1,2,3,4].map(j => <span key={j} style={{ fontSize: 10, color: "#F59E0B" }}>★</span>)}</div><div style={{ fontSize: 9, color: "#374151", lineHeight: 1.5 }}>"{rev.q}"</div></div></div>)}</div></div><div style={{ display: "flex", justifyContent: "center", gap: 6, marginTop: 10 }}>{[0,1,2].map(i => <div key={i} style={{ width: 6, height: 6, borderRadius: "50%", background: i === 0 ? P : "#D1D5DB" }} />)}</div></div></div><div style={{ padding: "0 28px 28px" }}><h3 style={{ fontFamily: HF, fontSize: 20, fontWeight: 700, margin: "0 0 8px", color: "#111827" }}>Testimonials & FAQ</h3><p style={{ fontSize: 14, color: "#6B7280", lineHeight: 1.65, margin: 0 }}>Add customer reviews with star ratings that display in a beautiful slider. Editable FAQ section answers common questions automatically.</p></div></div>
          {/* Orders to Print card */}
          <div className="bento-card" style={{ background: "#fff", borderRadius: 24, border: "1px solid #E5E7EB", overflow: "hidden", boxShadow: "0 2px 8px rgba(0,0,0,0.02)" }}><div style={{ padding: 20 }}><div style={{ background: tint.pink, borderRadius: 16, padding: 16 }}><div style={{ fontSize: 8, color: "#6B7280", fontWeight: 600, marginBottom: 8 }}>ORDER → DOWNLOAD → PRINT</div>
              <div style={{ background: "#fff", borderRadius: 10, padding: 10, border: "1px solid rgba(0,0,0,0.06)", marginBottom: 8 }}><div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 6 }}><div style={{ display: "flex", alignItems: "center", gap: 6 }}><div style={{ width: 6, height: 6, borderRadius: "50%", background: "#16A34A" }} /><span style={{ fontSize: 9, fontWeight: 700, color: "#111827", fontFamily: "monospace" }}>DTF-X7K3D9</span></div><span style={{ fontSize: 8, padding: "2px 8px", borderRadius: 99, background: "#F0FDF4", color: "#16A34A", fontWeight: 600 }}>Paid</span></div><div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 6 }}><span style={{ fontSize: 8, color: "#6B7280" }}>Ravi K. · 1 sheet · 22×38"</span></div><div style={{ display: "flex", gap: 6 }}><div style={{ flex: 1, padding: "6px 0", borderRadius: 6, background: P, fontSize: 8, fontWeight: 600, color: "#fff", textAlign: "center", display: "flex", alignItems: "center", justifyContent: "center", gap: 4 }}><svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" /><polyline points="7 10 12 15 17 10" /><line x1="12" y1="15" x2="12" y2="3" /></svg>Download PNG</div><div style={{ flex: 1, padding: "6px 0", borderRadius: 6, background: "#F3F4F6", fontSize: 8, fontWeight: 600, color: "#374151", textAlign: "center" }}>Mark Done</div></div></div>
              <div style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: 6, padding: "8px 0" }}>{[{ l: "Download", ic: <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" /><polyline points="7 10 12 15 17 10" /><line x1="12" y1="15" x2="12" y2="3" /></svg>, c: P }, { l: "Print", ic: <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2"><polyline points="6 9 6 2 18 2 18 9" /><path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2" /><rect x="6" y="14" width="12" height="8" /></svg>, c: "#059669" }, { l: "Dispatch", ic: <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2"><rect x="1" y="3" width="15" height="13" /><polygon points="16 8 20 8 23 11 23 16 16 16 16 8" /><circle cx="5.5" cy="18.5" r="2.5" /><circle cx="18.5" cy="18.5" r="2.5" /></svg>, c: "#D97706" }].map((s, i) => <div key={i} style={{ display: "flex", alignItems: "center" }}><div style={{ textAlign: "center" }}><div style={{ width: 32, height: 32, borderRadius: 10, background: s.c, display: "flex", alignItems: "center", justifyContent: "center", margin: "0 auto 3px" }}>{s.ic}</div><div style={{ fontSize: 7, fontWeight: 600, color: "#374151" }}>{s.l}</div></div>{i < 2 && <svg width="16" height="8" viewBox="0 0 16 8" fill="none" style={{ margin: "0 4px", marginBottom: 12 }}><path d="M1 4h12M11 1l3 3-3 3" stroke="#D1D5DB" strokeWidth="1.5" strokeLinecap="round" /></svg>}</div>)}</div>
            </div></div><div style={{ padding: "0 28px 28px" }}><h3 style={{ fontFamily: HF, fontSize: 20, fontWeight: 700, margin: "0 0 8px", color: "#111827" }}>Download & Print</h3><p style={{ fontSize: 14, color: "#6B7280", lineHeight: 1.65, margin: 0 }}>Download print-ready gang sheet PNGs with embedded DPI metadata. Send straight to your printer and dispatch to customers.</p></div></div>
        </div>
        {/* 5-Step Customer Journey */}
        <div style={{ marginTop: 72, padding: "48px 0", background: "#fff", borderRadius: 24, border: "1px solid #E5E7EB", boxShadow: "0 2px 8px rgba(0,0,0,0.02)" }}>
          <div style={{ textAlign: "center", marginBottom: 36 }}><div style={{ fontSize: 12, fontWeight: 600, color: P, textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: 8, fontFamily: BF }}>How It Works for Your Customers</div><h3 style={{ fontFamily: HF, fontSize: 28, fontWeight: 800, color: "#111827", margin: 0 }}>From Visit to Dispatch in 5 Steps</h3></div>
          <div style={{ display: "flex", flexWrap: isMobile ? "wrap" : "nowrap", alignItems: "flex-start", justifyContent: "center", gap: 0, padding: "0 16px" }}>
            {[{ n: "1", t: "Visit Your Website", d: <span>Customer opens <span style={{ whiteSpace: "nowrap" }}>your-store.dtflayout.com</span></span>, ic: <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2"><circle cx="12" cy="12" r="10" /><line x1="2" y1="12" x2="22" y2="12" /><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10A15.3 15.3 0 0 1 12 2z" /></svg>, c: P },
              { n: "2", t: "Upload Images", d: "Drags in their design files", ic: <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" /><polyline points="17 8 12 3 7 8" /><line x1="12" y1="3" x2="12" y2="15" /></svg>, c: "#7C3AED" },
              { n: "3", t: "Generate Sheets", d: "Single or multi-sheet layouts", ic: <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2"><rect x="3" y="3" width="18" height="18" rx="2" /><circle cx="8.5" cy="8.5" r="1.5" /><polyline points="21 15 16 10 5 21" /></svg>, c: "#A855F7" },
              { n: "4", t: "Place Order", d: "Name + phone + email needed", ic: <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" /><polyline points="22 4 12 14.01 9 11.01" /></svg>, c: "#059669" },
              { n: "5", t: "You Print & Dispatch", d: "Download, print, ship. Payment offline.", ic: <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2"><polyline points="6 9 6 2 18 2 18 9" /><path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2" /><rect x="6" y="14" width="12" height="8" /></svg>, c: "#D97706" }
            ].map((s, i) => (
              <div key={i} style={{ display: "flex", alignItems: "flex-start", ...(isMobile ? { width: "50%", justifyContent: "center", marginBottom: 20 } : {}) }}>
                <div style={{ textAlign: "center", width: isMobile ? undefined : 160, flexShrink: 0 }}>
                  <div style={{ width: 64, height: 64, borderRadius: 18, background: `linear-gradient(135deg, ${s.c}, ${s.c}cc)`, display: "flex", alignItems: "center", justifyContent: "center", margin: "0 auto 12px", boxShadow: `0 6px 20px ${s.c}35`, position: "relative" }}>{s.ic}<div style={{ position: "absolute", top: -5, right: -5, width: 22, height: 22, borderRadius: "50%", background: "#fff", border: `2px solid ${s.c}`, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 11, fontWeight: 800, color: s.c, fontFamily: HF }}>{s.n}</div></div>
                  <div style={{ fontSize: 16, fontWeight: 700, color: "#111827", marginBottom: 6, fontFamily: HF }}>{s.t}</div>
                  <div style={{ fontSize: 13, color: "#6B7280", lineHeight: 1.5 }}>{s.d}</div>
                </div>
                {i < 4 && !isMobile && <div style={{ display: "flex", alignItems: "center", height: 64, flexShrink: 0, margin: "0 2px" }}><svg width="28" height="12" viewBox="0 0 28 12" fill="none"><path d="M2 6h22M20 2l5 4-5 4" stroke="#C7D2FE" strokeWidth="2" strokeLinecap="round" /></svg></div>}
              </div>
            ))}
          </div>
        </div>
      </div></section>
      <section style={{ padding: isMobile ? "60px 16px" : "120px 40px", position: "relative" }}><Dots o={0.06} /><div style={{ maxWidth: 1060, margin: "0 auto", position: "relative", zIndex: 1 }}><div style={{ display: "grid", gridTemplateColumns: isMobile ? "1fr" : "1fr 1.15fr", gap: 48, alignItems: "center" }}><div><Pill>Embedded Builder</Pill><h2 style={{ fontFamily: HF, fontSize: isMobile ? 26 : 40, fontWeight: 800, color: "#111827", lineHeight: 1.1, letterSpacing: "-0.03em", margin: "20px 0 12px" }}>Same Powerful Builder. Your Brand. Your Logo.</h2><p style={{ fontSize: 15, color: "#6B7280", lineHeight: 1.7, margin: "0 0 32px" }}>The gang sheet builder your customers use is the same one powering our core product — auto-arrangement, image editing tools, multi-sheet support — all embedded directly in your website.</p><div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>{["Auto-Arrange", "Trim & Flip", "Remove BG", "Replace Color", "Text Overlay", "Multi-Sheet", "150 / 300 DPI", "Up to 80 Images"].map((t, i) => <span key={i} style={{ padding: "6px 14px", borderRadius: 99, fontSize: 12, fontWeight: 600, background: "#EEF2FF", color: P, border: "1px solid #C7D2FE" }}>{t}</span>)}</div></div>
        <div className="bento-card" style={{ background: "#fff", borderRadius: 20, border: "1px solid #E5E7EB", boxShadow: "0 16px 48px rgba(0,0,0,0.06)", overflow: "hidden" }}><div style={{ padding: 20 }}><div style={{ background: tint.peach, borderRadius: 14, padding: 16 }}><div style={{ background: st.color, padding: "6px 14px", borderRadius: "10px 10px 0 0", display: "flex", alignItems: "center", justifyContent: "space-between", transition: "background 0.4s" }}><div style={{ display: "flex", alignItems: "center", gap: 6 }}><div style={{ width: 18, height: 18, borderRadius: 5, background: "rgba(255,255,255,0.2)", display: "flex", alignItems: "center", justifyContent: "center" }}><svg width="8" height="8" viewBox="0 0 24 24" fill="#fff"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z" /></svg></div><span style={{ fontSize: 10, fontWeight: 700, color: "#fff", fontFamily: HF, transition: "all 0.4s" }}>{st.name}</span></div><span style={{ fontSize: 8, color: "rgba(255,255,255,0.7)" }}>Products / Standard DTF</span></div><div style={{ background: "#fff", borderRadius: "0 0 10px 10px", padding: 14, border: "1px solid #E5E7EB", borderTop: "none" }}><div style={{ textAlign: "center", marginBottom: 8 }}><div style={{ fontSize: 13, fontWeight: 700, color: "#111827", fontFamily: HF }}>Create Your Gang Sheet</div><div style={{ fontSize: 9, color: "#9CA3AF" }}>Upload designs and generate optimized layouts</div></div><div style={{ display: "flex", gap: 10, justifyContent: "center", marginBottom: 10 }}>{["Trim", "Flip", "Remove BG", "Text"].map((t, i) => <div key={i} style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 2 }}><div style={{ width: 28, height: 28, borderRadius: "50%", background: i === 0 ? st.color : ["#0EA5E9", "#A855F7", st.color][i-1], display: "flex", alignItems: "center", justifyContent: "center", transition: "background 0.4s" }}><svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2.5"><path d="M12 5v14M5 12h14" /></svg></div><span style={{ fontSize: 6, color: "#9CA3AF" }}>{t}</span></div>)}</div><div style={{ display: "grid", gridTemplateColumns: isMobile ? "1fr" : "repeat(3,1fr)", gap: 4, marginBottom: 8 }}>{[0,1,2].map(i => <div key={i} style={{ height: 44, borderRadius: 6, background: `linear-gradient(135deg,${["#E74C3C", "#3498DB", "#2ECC71"][i]}44,${["#E74C3C", "#3498DB", "#2ECC71"][i]}22)`, border: "1px solid #E5E7EB" }} />)}</div><div style={{ background: st.color, padding: "7px 12px", borderRadius: 8, display: "flex", justifyContent: "space-between", alignItems: "center", transition: "background 0.4s" }}><span style={{ fontSize: 9, color: "rgba(255,255,255,0.7)" }}>3 Images · 22" wide</span><span style={{ fontSize: 9, fontWeight: 600, color: st.color, background: "#fff", padding: "3px 12px", borderRadius: 6, transition: "color 0.4s" }}>Generate Layout</span></div></div></div></div></div>
      </div></div></section>

      {/* ORDER MANAGEMENT */}
      <section style={{ padding: isMobile ? "60px 16px" : "120px 40px", background: "#FAFAFB", position: "relative" }}><Dots o={0.06} /><div style={{ maxWidth: 1060, margin: "0 auto", position: "relative", zIndex: 1 }}><div style={{ display: "grid", gridTemplateColumns: isMobile ? "1fr" : "1.2fr 1fr", gap: 48, alignItems: "center" }}>
        <div style={{ borderRadius: 20, overflow: "hidden", border: "1px solid #E5E7EB", boxShadow: "0 16px 48px rgba(0,0,0,0.06)", background: "#fff" }}><div style={{ padding: "12px 16px", borderBottom: "1px solid #F3F4F6", display: "flex", alignItems: "center", gap: 6 }}><span style={{ fontSize: 10, color: "#9CA3AF", fontWeight: 500 }}>Period:</span>{["Today", "This Week", "All Time"].map((p, i) => <span key={i} style={{ padding: "4px 10px", borderRadius: 8, fontSize: 9, fontWeight: 600, background: i === 2 ? P : "#F3F4F6", color: i === 2 ? "#fff" : "#6B7280" }}>{p}</span>)}</div><div style={{ display: "flex", gap: 0, borderBottom: "1px solid #E5E7EB" }}>{[{ n: "24", l: "Total", c: "#111827" }, { n: "5", l: "Pending", c: "#F59E0B" }, { n: "3", l: "Paid", c: "#16A34A" }, { n: "16", l: "Downloaded", c: "#3B82F6" }].map((s, i) => <div key={i} style={{ flex: 1, padding: "14px 16px", borderRight: i < 3 ? "1px solid #F3F4F6" : "none" }}><div style={{ fontSize: 20, fontWeight: 800, fontFamily: HF, color: s.c }}>{s.n}</div><div style={{ fontSize: 10, color: "#9CA3AF" }}>{s.l}</div></div>)}</div><div style={{ padding: "10px 16px 6px", display: "flex", alignItems: "center", justifyContent: "space-between" }}><span style={{ fontSize: 13, fontWeight: 700, color: "#111827", fontFamily: HF }}>Customer Orders</span><div style={{ display: "flex", gap: 4 }}>{["Kanban", "Table"].map((v, i) => <span key={i} style={{ padding: "4px 12px", borderRadius: 8, fontSize: 10, fontWeight: 600, background: i === 0 ? P : "#F3F4F6", color: i === 0 ? "#fff" : "#6B7280" }}>{v}</span>)}</div></div>
          <div style={{ display: "grid", gridTemplateColumns: isMobile ? "1fr" : "1fr 1fr 1fr", gap: 8, padding: "8px 12px 14px" }}>{[{ l: "Pending", c: "#F59E0B", bg: "#FFFBEB", cards: [{ code: "DTF-X7K3D9", name: "Ravi K.", price: "$14" }, { code: "DTF-A2BFHL", name: "Priya M.", price: "$8" }] }, { l: "Paid", c: "#16A34A", bg: "#F0FDF4", cards: [{ code: "DTF-R9WNXE", name: "Amit S.", price: "$20" }] }, { l: "Downloaded", c: "#3B82F6", bg: "#EFF6FF", cards: [{ code: "DTF-V4JTQD", name: "Sara L.", price: "$17" }, { code: "DTF-BGHL03", name: "Kiran R.", price: "$11" }] }].map((col, i) => (<div key={i} style={{ borderRadius: 12, border: "1px solid #E5E7EB", overflow: "hidden" }}><div style={{ padding: "8px 10px", display: "flex", alignItems: "center", justifyContent: "space-between", background: col.bg }}><div style={{ display: "flex", alignItems: "center", gap: 5 }}><div style={{ width: 7, height: 7, borderRadius: "50%", background: col.c }} /><span style={{ fontSize: 10, fontWeight: 700, color: "#111827" }}>{col.l}</span></div><span style={{ fontSize: 9, fontWeight: 600, color: col.c, background: "#fff", padding: "1px 6px", borderRadius: 99 }}>{col.cards.length}</span></div><div style={{ padding: 6, minHeight: 100, background: `${col.bg}80` }}>{col.cards.map((card, j) => <div key={j} style={{ background: "#fff", borderRadius: 8, padding: "8px 9px", border: "1px solid #E5E7EB", marginBottom: j < col.cards.length - 1 ? 5 : 0 }}><div style={{ fontSize: 9, fontWeight: 700, color: "#111827", fontFamily: "monospace" }}>{card.code}</div><div style={{ fontSize: 8, color: "#6B7280", marginTop: 2 }}>{card.name}</div><div style={{ display: "flex", justifyContent: "space-between", marginTop: 3 }}><span style={{ fontSize: 8, fontWeight: 600, color: "#111827" }}>{card.price}</span><span style={{ fontSize: 8, color: col.c, fontWeight: 500 }}>1 sheet</span></div></div>)}</div></div>))}</div>
        </div>
        <div><Pill>Order Management</Pill><h2 style={{ fontFamily: HF, fontSize: isMobile ? 26 : 40, fontWeight: 800, color: "#111827", lineHeight: 1.1, letterSpacing: "-0.03em", margin: "20px 0 12px" }}>Track Every Order from Your Dashboard</h2><p style={{ fontSize: 15, color: "#6B7280", lineHeight: 1.7, margin: "0 0 32px" }}>Customers submit orders from your website. You manage everything from one dashboard — download gang sheet files, track payments, and fulfill orders.</p><div style={{ display: "flex", flexDirection: "column", gap: 18 }}>{[{ t: "Kanban + Table Views", d: "Drag orders between columns or switch to table view for bulk management. Filter by date range or quick presets." }, { t: "Real File Downloads", d: "Download the actual gang sheet PNGs your customers generated. Print-ready with embedded DPI metadata." }, { t: "No Auth for Customers", d: "Customers just enter their name and phone number. No accounts, no passwords, no friction." }, { t: "Auto-Expiry & Cleanup", d: "Unclaimed orders expire after 10 days. One-click cleanup keeps your dashboard focused." }].map((f, i) => <div key={i} style={{ display: "flex", gap: 14, alignItems: "flex-start" }}><div style={{ width: 8, height: 8, borderRadius: "50%", background: P, marginTop: 6, flexShrink: 0 }} /><div><div style={{ fontSize: 15, fontWeight: 700, color: "#111827", marginBottom: 3 }}>{f.t}</div><div style={{ fontSize: 13, color: "#6B7280", lineHeight: 1.6 }}>{f.d}</div></div></div>)}</div></div>
      </div></div></section>

      {/* INTERACTIVE DEMO */}
      <section style={{ padding: isMobile ? "60px 16px" : "100px 40px", position: "relative" }}>
        <Dots o={0.06} />
        <div style={{ maxWidth: 900, margin: "0 auto", position: "relative", zIndex: 1 }}>
          <div style={{ borderRadius: 28, overflow: "hidden", background: "linear-gradient(140deg, #0f0d2e 0%, #1e1b4b 30%, #312e81 60%, #4338ca 100%)", boxShadow: "0 16px 56px rgba(30,27,75,0.35)", position: "relative" }}>
            <div style={{ position: "absolute", top: -40, right: -40, width: 160, height: 160, borderRadius: "50%", background: "radial-gradient(circle, rgba(129,140,248,0.15) 0%, transparent 70%)" }} />
            <div style={{ position: "absolute", bottom: -30, left: -30, width: 100, height: 100, borderRadius: "50%", background: "radial-gradient(circle, rgba(99,102,241,0.12) 0%, transparent 70%)" }} />
            <div style={{ padding: isMobile ? "32px 24px" : "48px 48px", display: "flex", flexDirection: isMobile ? "column" : "row", alignItems: "center", gap: isMobile ? 24 : 40, position: "relative", zIndex: 1 }}>
              <div style={{ flex: 1 }}>
                <div style={{ display: "inline-flex", alignItems: "center", gap: 6, padding: "5px 14px", borderRadius: 99, background: "rgba(52,211,153,0.12)", border: "1px solid rgba(52,211,153,0.2)", marginBottom: 16 }}>
                  <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="#34d399" strokeWidth="2.5"><polygon points="5 3 19 12 5 21 5 3" /></svg>
                  <span style={{ fontSize: 12, fontWeight: 700, color: "#34d399", letterSpacing: "0.05em" }}>INTERACTIVE DEMO</span>
                </div>
                <h2 style={{ fontFamily: HF, fontSize: isMobile ? 24 : 32, fontWeight: 800, color: "#fff", lineHeight: 1.15, letterSpacing: "-0.02em", margin: "0 0 12px" }}>See the Builder In Action</h2>
                <p style={{ fontSize: isMobile ? 14 : 15, color: "rgba(255,255,255,0.6)", lineHeight: 1.7, margin: "0 0 24px" }}>Try the live builder demo. Change colors, upload your logo, pick fonts — see exactly how it will look for your customers.</p>
                <Btn sz="m" onClick={() => navigate("/demo/builder-live")} style={{ background: "#fff", color: P, boxShadow: "0 6px 24px rgba(0,0,0,0.15)" }}>Try Live Demo →</Btn>
              </div>
              {!isMobile && <div style={{ flex: "0 0 auto", width: 260, height: 200, borderRadius: 16, background: "rgba(255,255,255,0.06)", border: "1px solid rgba(255,255,255,0.1)", display: "flex", flexDirection: "column", overflow: "hidden" }}>
                <div style={{ padding: "6px 10px", background: "#1e293b", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 5 }}><div style={{ width: 16, height: 16, borderRadius: 4, background: "rgba(79,70,229,0.3)" }} /><span style={{ fontSize: 8, fontWeight: 700, color: "#fff" }}>Your Store</span></div>
                  <span style={{ fontSize: 6, fontWeight: 600, padding: "2px 8px", borderRadius: 4, background: "#4F46E5", color: "#fff" }}>Add to Cart</span>
                </div>
                <div style={{ flex: 1, background: "#f1f5f9", padding: "8px", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 6 }}>
                  <div style={{ display: "flex", gap: 4 }}>{["#4F46E5", "#0EA5E9", "#A855F7", "#F59E0B"].map((c, i) => <div key={i} style={{ width: 18, height: 18, borderRadius: "50%", background: c }} />)}</div>
                  <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 3, width: "80%" }}>{[1, 2, 3].map(i => <div key={i} style={{ height: 24, borderRadius: 3, background: "#fff", border: "1px solid #E5E7EB" }} />)}</div>
                  <div style={{ fontSize: 7, color: "#9CA3AF", fontWeight: 500 }}>Change any color, font, or style</div>
                </div>
                <div style={{ padding: "4px 10px", background: "#1e293b", display: "flex", justifyContent: "flex-end", gap: 3 }}>
                  <span style={{ fontSize: 5, padding: "2px 6px", borderRadius: 3, border: "1px solid rgba(255,255,255,0.2)", color: "rgba(255,255,255,0.5)" }}>Preview</span>
                  <span style={{ fontSize: 5, padding: "2px 6px", borderRadius: 3, background: "#4F46E5", color: "#fff" }}>Generate</span>
                </div>
              </div>}
            </div>
          </div>
        </div>
      </section>

      {/* WHY QUICK STORE */}
      <section style={{ padding: isMobile ? "60px 16px" : "120px 40px", background: "linear-gradient(180deg, #0F0D2E, #1E1B4B, #312E81)", position: "relative", overflow: "hidden" }}><MovingPattern /><div style={{ maxWidth: 1060, margin: "0 auto", position: "relative", zIndex: 1 }}><div style={{ textAlign: "center", marginBottom: 64 }}><Pill>Why Quick Store?</Pill><h2 style={{ fontFamily: HF, fontSize: isMobile ? 26 : 44, fontWeight: 800, color: "#fff", lineHeight: 1.1, letterSpacing: "-0.03em", margin: "20px 0 12px" }}>Stop Running Your Business Through WhatsApp</h2><p style={{ fontSize: 16, color: "rgba(255,255,255,0.6)", lineHeight: 1.7, maxWidth: 540, margin: "0 auto" }}>Every order that comes through a DM or phone call is time you could spend printing.</p></div>
        <div style={{ display: "grid", gridTemplateColumns: isMobile ? "1fr" : "1fr 1fr", gap: 32, marginBottom: 48 }}>
          <div style={{ background: "rgba(255,255,255,0.92)", borderRadius: 24, border: "1px solid rgba(255,255,255,0.6)", padding: 36, backdropFilter: "blur(20px)", boxShadow: "0 8px 32px rgba(0,0,0,0.12)" }}><div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 20 }}><div style={{ width: 40, height: 40, borderRadius: 10, background: "rgba(239,68,68,0.12)", display: "flex", alignItems: "center", justifyContent: "center" }}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#EF4444" strokeWidth="2" strokeLinecap="round"><circle cx="12" cy="12" r="10" /><path d="M12 6v6l4 2" /></svg></div><div><div style={{ fontSize: 16, fontWeight: 700, color: "#1E1B4B" }}>Without Quick Store</div><div style={{ fontSize: 12, color: "#6B7280" }}>Manual everything</div></div></div>{["Customer sends designs via WhatsApp", "You manually quote based on dimensions", "Back-and-forth on pricing and sizes", "Collect payment via bank transfer or invoice", "No online presence — word of mouth only"].map((step, i) => <div key={i} style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 14 }}><div style={{ width: 24, height: 24, borderRadius: 99, background: "rgba(239,68,68,0.1)", border: "1px solid rgba(239,68,68,0.2)", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0, fontSize: 10, fontWeight: 700, color: "#EF4444" }}>{i + 1}</div><span style={{ fontSize: 14, color: "#374151" }}>{step}</span></div>)}<div style={{ marginTop: 20, padding: 16, borderRadius: 12, background: "rgba(239,68,68,0.06)", border: "1px solid rgba(239,68,68,0.15)", textAlign: "center" }}><div style={{ fontFamily: "monospace", fontSize: 28, fontWeight: 700, color: "#EF4444" }}>Hours per day</div><div style={{ fontSize: 12, color: "#6B7280", marginTop: 4 }}>On WhatsApp & phone calls</div></div></div>
          <div style={{ background: "rgba(255,255,255,0.92)", borderRadius: 24, border: "1px solid rgba(99,102,241,0.25)", padding: 36, backdropFilter: "blur(20px)", boxShadow: "0 8px 32px rgba(79,70,229,0.12)" }}><div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 20 }}><div style={{ width: 40, height: 40, borderRadius: 10, background: "rgba(79,70,229,0.1)", display: "flex", alignItems: "center", justifyContent: "center" }}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#6366F1" strokeWidth="2" strokeLinecap="round"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2" /></svg></div><div><div style={{ fontSize: 16, fontWeight: 700, color: "#1E1B4B" }}>With Quick Store</div><div style={{ fontSize: 12, color: "#6B7280" }}>Professional & automated</div></div></div>{["Customer visits your-store.dtflayout.com", "Browses your products and pricing", "Creates gang sheet using built-in builder", "Submits order with name + phone — done", "You download files and fulfill when ready"].map((step, i) => <div key={i} style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 14 }}><div style={{ width: 24, height: 24, borderRadius: 99, background: "rgba(79,70,229,0.1)", border: "1px solid rgba(99,102,241,0.2)", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="#6366F1" strokeWidth="2.5"><path d="M5 13l4 4L19 7" /></svg></div><span style={{ fontSize: 14, color: "#374151" }}>{step}</span></div>)}<div style={{ marginTop: 20, padding: 16, borderRadius: 12, background: "rgba(79,70,229,0.06)", border: "1px solid rgba(99,102,241,0.2)", textAlign: "center" }}><div style={{ fontFamily: "monospace", fontSize: 28, fontWeight: 700, color: "#4F46E5" }}>Fully automated</div><div style={{ fontSize: 12, color: "#6B7280", marginTop: 4 }}>24/7 ordering, zero effort</div></div></div>
        </div>
        <div style={{ display: "grid", gridTemplateColumns: isMobile ? "1fr 1fr" : "repeat(4,1fr)", gap: 16 }}>{[{ n: "Your URL", l: "store.dtflayout.com" }, { n: "7", l: "Currencies supported" }, { n: "24/7", l: "Always-on ordering" }, { n: "Zero", l: "Code required" }].map((s, i) => <div key={i} style={{ textAlign: "center", padding: "20px 0", borderRadius: 16, background: "rgba(255,255,255,0.88)", border: "1px solid rgba(255,255,255,0.5)", backdropFilter: "blur(16px)", boxShadow: "0 4px 16px rgba(0,0,0,0.08)" }}><div style={{ fontSize: 24, fontWeight: 800, fontFamily: HF, color: P }}>{s.n}</div><div style={{ fontSize: 12, color: "#6B7280", marginTop: 4 }}>{s.l}</div></div>)}</div>
      </div></section>

      {/* CTA */}
      <section style={{ padding: isMobile ? "60px 16px" : "120px 40px", position: "relative", overflow: "hidden" }}><Dots o={0.1} /><Sq top={60} right={160} size={34} rotate={15} /><Sq bottom={60} left={140} size={28} rotate={-20} /><div style={{ maxWidth: 620, margin: "0 auto", textAlign: "center", position: "relative", zIndex: 1 }}><h2 style={{ fontFamily: HF, fontSize: isMobile ? 26 : 44, fontWeight: 800, color: "#111827", lineHeight: 1.1, letterSpacing: "-0.03em", margin: "0 0 18px" }}>Launch Your Store in Minutes</h2><p style={{ fontSize: 16, color: "#6B7280", lineHeight: 1.7, margin: "0 0 40px" }}>Start with 20,000 sq.inch free. No credit card required. No monthly fees, ever.</p><div style={{ display: "flex", justifyContent: "center", gap: 14 }}><Btn sz="l" onClick={() => navigate("/signup")}>Create Your Store Free →</Btn><Btn v="o" sz="l" onClick={() => navigate("/pricing")}>View Pricing →</Btn></div></div></section>

      {/* FOOTER */}
      <footer style={{ position: "relative", padding: isMobile ? "0 16px 24px" : "0 40px 32px", background: "linear-gradient(180deg, #1E1B4B, #0F0D2E)", color: "rgba(165,180,252,0.6)" }}><div style={{ position: "absolute", top: 0, left: 0, right: 0, height: 1, background: "linear-gradient(90deg, transparent 5%, rgba(99,102,241,0.3) 20%, rgba(129,140,248,0.5) 50%, rgba(99,102,241,0.3) 80%, transparent 95%)" }} /><div style={{ paddingTop: 64 }}><div style={{ maxWidth: 1060, margin: "0 auto" }}><div style={{ display: "grid", gridTemplateColumns: isMobile ? "1fr" : "2fr 1fr 1fr 1fr", gap: 48, marginBottom: 48 }}><div><div style={{ display: "flex", alignItems: "center", gap: 7, marginBottom: 16 }}><div style={{ width: 28, height: 28, borderRadius: 7, background: "#10B981", display: "flex", alignItems: "center", justifyContent: "center" }}><svg width="12" height="12" viewBox="0 0 24 24" fill="#fff"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z" /></svg></div><span style={{ fontFamily: HF, fontWeight: 700, fontSize: 15, color: "#fff" }}>DTF Layout</span></div><p style={{ fontSize: 14, lineHeight: 1.7, maxWidth: 260 }}>Smart DTF sheet builder for printers worldwide. Auto-arrange, optimize, and print — all from one platform.</p></div><div><h4 style={{ fontSize: 11, fontWeight: 600, color: "#A5B4FC", marginBottom: 16, letterSpacing: "0.08em", textTransform: "uppercase" }}>Product</h4>{[{l:"Gang Sheet Builder",to:"/product/gang-sheet-builder"},{l:"Website Integration",to:"/product/website-integration"},{l:"Quick Store",to:"/product/quick-store"},{l:"Pricing",to:"/pricing"}].map(item => <Link key={item.l} to={item.to} style={{ fontSize: 14, marginBottom: 10, display: "block", color: "inherit", textDecoration: "none" }}>{item.l}</Link>)}</div><div><h4 style={{ fontSize: 11, fontWeight: 600, color: "#A5B4FC", marginBottom: 16, letterSpacing: "0.08em", textTransform: "uppercase" }}>Company</h4>{[{l:"FAQ",to:"/faq"},{l:"Contact",to:"/contact"},{l:"Blog",to:"/"}].map(item => <Link key={item.l} to={item.to} style={{ fontSize: 14, marginBottom: 10, display: "block", color: "inherit", textDecoration: "none" }}>{item.l}</Link>)}</div><div><h4 style={{ fontSize: 11, fontWeight: 600, color: "#A5B4FC", marginBottom: 16, letterSpacing: "0.08em", textTransform: "uppercase" }}>Legal</h4>{[{l:"Privacy Policy",to:"/privacy-policy"},{l:"Terms & Conditions",to:"/terms-conditions"},{l:"Refund Policy",to:"/refund-policy"}].map(item => <Link key={item.l} to={item.to} style={{ fontSize: 14, marginBottom: 10, display: "block", color: "inherit", textDecoration: "none" }}>{item.l}</Link>)}</div></div><div style={{ borderTop: "1px solid rgba(99,102,241,0.12)", paddingTop: 24, display: "flex", justifyContent: "space-between", alignItems: "center" }}><span style={{ fontSize: 13 }}>© 2026 DTF Layout · Data Canvas Tech. All rights reserved.</span><span style={{ fontSize: 13, cursor: "pointer" }}>support@dtflayout.com</span></div></div></div></footer>
    </div>
  );
}
